package com.internship.backend;

import com.internship.backend.dto.TaskRequestDTO;
import com.internship.backend.dto.TaskResponseDTO;
import com.internship.backend.enums.Priority;
import com.internship.backend.enums.Status;
import com.internship.backend.repository.TaskRepository;
import com.internship.backend.service.TaskService;
import io.cucumber.datatable.DataTable;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.cucumber.spring.CucumberContextConfiguration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@CucumberContextConfiguration
@SpringBootTest
@org.springframework.test.context.ActiveProfiles("test")
public class TaskStepDefinitions {

    @Autowired
    private TaskService taskService;

    @Autowired
    private TaskRepository taskRepository;

    private TaskResponseDTO currentTask;
    private Long currentTaskId;
    private List<TaskResponseDTO> queryResults;

    @Given("the task system is ready")
    public void the_task_system_is_ready() {
        taskRepository.deleteAll();
    }

    @When("I create a task titled {string} with priority {string} and status {string}")
    public void i_create_a_task_titled_with_priority_and_status(String title, String priority, String status) {
        TaskRequestDTO request = TaskRequestDTO.builder()
                .title(title)
                .priority(Priority.valueOf(priority))
                .status(Status.valueOf(status))
                .build();
        currentTask = taskService.createTask(request);
        currentTaskId = currentTask.getId();
    }

    @Then("the task should be saved successfully with a generated ID")
    public void the_task_should_be_saved_successfully_with_a_generated_id() {
        assertNotNull(currentTaskId, "Task ID should be generated by the database");
    }

    @Then("the task status should be {string}")
    public void the_task_status_should_be(String expectedStatus) {
        assertEquals(Status.valueOf(expectedStatus), currentTask.getStatus());
    }

    @Given("I have an existing task titled {string} with status {string} and priority {string}")
    public void i_have_an_existing_task_titled_with_status_and_priority(String title, String status, String priority) {
        TaskRequestDTO request = TaskRequestDTO.builder()
                .title(title)
                .status(Status.valueOf(status))
                .priority(Priority.valueOf(priority))
                .build();
        currentTask = taskService.createTask(request);
        currentTaskId = currentTask.getId(); // Capture the ID
    }

    @When("I change the task status by its ID to {string}")
    public void i_change_the_task_status_by_its_id_to(String newStatus) {
        TaskRequestDTO updateRequest = TaskRequestDTO.builder()
                .title(currentTask.getTitle())
                .description(currentTask.getDescription())
                .status(Status.valueOf(newStatus))
                .priority(currentTask.getPriority())
                .build();
        currentTask = taskService.updateTask(currentTaskId, updateRequest);
    }

    @Then("the task status should be updated to {string}")
    public void the_task_status_should_be_updated_to(String expectedStatus) {
        assertEquals(Status.valueOf(expectedStatus), currentTask.getStatus());
    }

    @When("I change the task priority by its ID to {string}")
    public void i_change_the_task_priority_by_its_id_to(String newPriority) {
        TaskRequestDTO updateRequest = TaskRequestDTO.builder()
                .title(currentTask.getTitle())
                .description(currentTask.getDescription())
                .status(currentTask.getStatus())
                .priority(Priority.valueOf(newPriority))
                .build();
        currentTask = taskService.updateTask(currentTaskId, updateRequest);
    }

    @Then("the task priority should be updated to {string}")
    public void the_task_priority_should_be_updated_to(String expectedPriority) {
        assertEquals(Priority.valueOf(expectedPriority), currentTask.getPriority());
    }

    @When("I delete the task by its ID")
    public void i_delete_the_task_by_its_id() {
        taskService.deleteTask(currentTaskId);
    }

    @Then("the task should no longer exist in the database")
    public void the_task_should_no_longer_exist_in_the_database() {
        assertThrows(ResponseStatusException.class, () -> {
            taskService.getTaskById(currentTaskId);
        }, "Expected TaskService to throw a 404 when fetching a deleted task");
    }

    @Given("my task list contains the following tasks:")
    public void my_task_list_contains_the_following_tasks(DataTable dataTable) {
        taskRepository.deleteAll();
        List<Map<String, String>> rows = dataTable.asMaps(String.class, String.class);
        for (Map<String, String> row : rows) {
            TaskRequestDTO request = TaskRequestDTO.builder()
                    .title(row.get("Title"))
                    .status(Status.valueOf(row.get("Status")))
                    .priority(Priority.valueOf(row.get("Priority")))
                    .build();
            taskService.createTask(request);
        }
    }

    @Given("my task list contains only {string} tasks")
    public void my_task_list_contains_only_tasks(String status) {
        taskRepository.deleteAll();
        TaskRequestDTO request = TaskRequestDTO.builder()
                .title("Sample Task")
                .status(Status.valueOf(status))
                .priority(Priority.LOW)
                .build();
        taskService.createTask(request);
    }

    @When("I filter my tasks by status {string}")
    public void i_filter_my_tasks_by_status(String status) {
        // Pass null for priority
        queryResults = taskService.getTasks(Status.valueOf(status), null);
    }

    @When("I filter my tasks by priority {string}")
    public void i_filter_my_tasks_by_priority(String priority) {
        // Pass null for status
        queryResults = taskService.getTasks(null, Priority.valueOf(priority));
    }

    @Then("I should see {int} task(s) in the results")
    public void i_should_see_tasks_in_the_results(Integer expectedCount) {
        assertEquals(expectedCount, queryResults.size());
    }

    @When("I filter my tasks by status {string} and priority {string}")
    public void i_filter_my_tasks_by_status_and_priority(String status, String priority) {
        queryResults = taskService.getTasks(Status.valueOf(status), Priority.valueOf(priority));
    }

}